[project]
name = "moonpies"
description = "Moon Polar Ice and Ejecta Stratigraphy model"
version = "1.1.0"
authors = [
    {name = "Christian J. Tai Udovicic", email = "cjtu@nau.edu"},
    {name = "Katelyn R. Frizzell"},
    {name = "Kristen M. Luchsinger"},
    {name = "Alissa Madera"},
    {name = "Tyler G. Paladino"}
]
maintainers = [
    {name = "Margaret Hansen", email = "margareh@andrew.cmu.edu"}
]
readme = "README.md"
requires-python = ">= 3.8"
license-files = ["LICENSE"]
classifiers = [
    'Intended Audience :: Science/Research',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: Astronomy',
    'Programming Language :: Python :: 3.8',
]
dependencies = [
    "numpy>1.17",
    "pandas>1.0",
    "matplotlib>3.3",
    "scipy>1.9.1",
    "gpytorch>1.11",
    "trimesh>4.7.1"
]

[project.urls]
Repository = "https://github.com/cjtu/moonpies"

[project.scripts]
moonpies = "moonpies.cli:run"
plot_moonpies = "moonpies.cli:plot"
moonpies_orig = "moonpies.cli:run_orig"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

